_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 12
                - 55
            "2":
                - 12
                - 55
            "3":
                - 23
                - 55
            "4": 3.10.0
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
